### ISSUE TITLE
states appear to require transitions

### ISSUE THREAD

**Issue by chmorgan** [hashmismatch/finny.rs#19]
It would be helpful if one could have a state that handles an event via an action but doesn't transition to another state.

**Comment by rudib** [comment]
Internal events do exactly that.

https://github.com/hashmismatch/finny.rs/blob/30433be3cedefd785b8ae11d24f6a03f49427aa3/finny_tests/tests/fsm_timers.rs#L50-L55

**Comment by chmorgan** [comment]
@rudib ahh thanks. Maybe I'll submit a PR to add this example to the README.md.
